# Generated by Django 2.2.12 on 2020-05-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200529_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sefrtg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sefdsf', models.BigIntegerField()),
            ],
        ),
    ]
