# Generated by Django 2.2.12 on 2020-05-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_customtext_gkjhgjhgkg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='gkjhgjhgkg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
