# Generated by Django 2.2.12 on 2020-05-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_customtext_kjhkh"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customtext", old_name="kjhkh", new_name="ghfnhgfgjh",
        ),
    ]
