# Generated by Django 2.2.12 on 2020-05-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_auto_20200529_0800"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="ghfnhgfgjh",),
    ]
